### ISSUE TITLE
Windows 7 import issue

### ISSUE THREAD

**Issue by oezgan** [scrapinghub/python-crfsuite#75]
Hey Guys,
working on windows 7 with a Python35-32 I have the following problem: 

```
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 15:51:26) [MSC v.1900 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycrfsuite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Daten\Python35-32\lib\site-packages\pycrfsuite\__init__.py", line 2,
in <module>
    from ._pycrfsuite import *
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
>>>
```
The error sates: "Could not find the module. " 
Can this be the case because of the "absolute import" in `__init__.py `? Since I am using a non-standard python path?
Thank you very much

**Comment by Smareddy309** [comment]
Hi oezgan, Did you find a fix to this yet?

**Comment by oezgan** [comment]
Hi, unfortunately i did not find the resolution to this problem. As far as i remember the issue araised because of another module using the crfsuite. I think i have abandoned that module and used another one.

**Comment by Smareddy309** [comment]
Thanks for the response. I am trying to use the 'usaddress' package and this seems to be the dependency issue that I am running into.

**Comment by aslesani** [comment]
I have this error as well. When I type :
`import pycrfsuite`  
I got the following error: 
` File "C:\Users\...\AppData\Local\Programs\Python\Python35\lib\site-packages\pycrfsuite\__init__.py", line 2, in <module>
    from ._pycrfsuite import *
ImportError: DLL load failed: The specified module could not be found.`

What should I do?

**Comment by oezgan** [comment]
Hi guys, 
I have checked this again, and magically it is working now: 

`C:\Users\user>python`
`Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 15:51:26) [MSC v.1900 32 bit (In
tel)] on win32`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import pycrfsuite`
`>>> `



I have even reinstalled it:
`C:\Users\user>pip install -I python-crfsuite
Collecting python-crfsuite
  Downloading https://files.pythonhosted.org/packages/fa/61/d7195693e44b64be473d
677fb6291b867fef9bbac2a275cbe76a13419672/python_crfsuite-0.9.5-cp35-cp35m-win32.
whl (124kB)
    100% |################################| 133kB 123kB/s
Installing collected packages: python-crfsuite
Successfully installed python-crfsuite-0.9.5`

I have no use for `crfsuite `  anymore, so I don't have any further details or insights.

**Comment by aslesani** [comment]
Dear @oezgan
Did you import it successfully? On one of my systems, it works without any problem but on another one, I have the following error:
ImportError: DLL load failed: The specified module could not be found.

**Comment by oezgan** [comment]
yes the import was successful. No error messages, but i cannot tell why.

**Comment by lbercken** [comment]
I was having this issue with 32 bit python 3.7 on Windows. When I installed 64 bit python 3.7 it magically worked.
